/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biblioteca_final;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kcnas
 */
public class Devolucao extends javax.swing.JFrame {

    /**
     * Creates new form Devolucao
     */
    public Devolucao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoDevLabel = new javax.swing.JLabel();
        codigoDevField = new javax.swing.JTextField();
        isbnDevLabel = new javax.swing.JLabel();
        isbnDevField = new javax.swing.JTextField();
        dataEmpDevLabel = new javax.swing.JLabel();
        dataEmpDevField = new javax.swing.JTextField();
        dataDevDevLabel = new javax.swing.JLabel();
        dataDevDevField = new javax.swing.JTextField();
        quatidadeDevLabel = new javax.swing.JLabel();
        quantidadeDevField = new javax.swing.JTextField();
        statusDevLabel = new javax.swing.JLabel();
        statusDevField = new javax.swing.JTextField();
        gerarDevButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Devolução");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        codigoDevLabel.setText("Código:");

        codigoDevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoDevFieldActionPerformed(evt);
            }
        });

        isbnDevLabel.setText("ISBN:");

        isbnDevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnDevFieldActionPerformed(evt);
            }
        });

        dataEmpDevLabel.setText("Data de Emprestimo:");

        dataEmpDevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataEmpDevFieldActionPerformed(evt);
            }
        });

        dataDevDevLabel.setText("Data de Devolução:");

        dataDevDevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDevDevFieldActionPerformed(evt);
            }
        });

        quatidadeDevLabel.setText("Quantidade:");

        quantidadeDevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeDevFieldActionPerformed(evt);
            }
        });

        statusDevLabel.setText("Status:");

        statusDevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusDevFieldActionPerformed(evt);
            }
        });

        gerarDevButton.setText("Gerar Devolução");
        gerarDevButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gerarDevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarDevButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gerarDevButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoDevLabel)
                            .addComponent(codigoDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataEmpDevLabel)
                            .addComponent(dataEmpDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quatidadeDevLabel)
                            .addComponent(quantidadeDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isbnDevLabel)
                            .addComponent(isbnDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataDevDevLabel)
                            .addComponent(dataDevDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusDevLabel)
                            .addComponent(statusDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoDevLabel)
                    .addComponent(isbnDevLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbnDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dataEmpDevLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataEmpDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dataDevDevLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataDevDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(quatidadeDevLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidadeDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(statusDevLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusDevField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(gerarDevButton)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoDevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoDevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoDevFieldActionPerformed

    private void isbnDevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnDevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnDevFieldActionPerformed

    private void dataEmpDevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataEmpDevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataEmpDevFieldActionPerformed

    private void dataDevDevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDevDevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDevDevFieldActionPerformed

    private void quantidadeDevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeDevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeDevFieldActionPerformed

    private void statusDevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusDevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusDevFieldActionPerformed

    private void gerarDevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarDevButtonActionPerformed
        try {
	Connection conexao = BancoDeDados.criarConn();
            int codigo = Integer.parseInt(codigoDevField.getText());
            int quantidade = Integer.parseInt(quantidadeDevField.getText());
            BancoDeDados.devolucao(
                    conexao, codigo, isbnDevField.getText(), dataEmpDevField.getText(),dataDevDevField.getText(), quantidade, statusDevField.getText()
            );
            System.out.println(codigoDevField.getText());
            System.out.println(isbnDevField.getText());
            System.out.println(dataEmpDevField.getText());
            System.out.println(dataDevDevField.getText());
            System.out.println(quantidadeDevField.getText());
            System.out.println(statusDevField.getText());
            
            dispose();
            Sucesso.telaSucesso();
             
        } catch (SQLException e) {
            e.printStackTrace();
		
       }



    }//GEN-LAST:event_gerarDevButtonActionPerformed

     public static void telaDevolucao(){
        
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Devolucao telaDev = new Devolucao();
               
                telaDev.setResizable(false);
                telaDev.requestFocusInWindow();
                telaDev.setLocationRelativeTo(null);
                telaDev.setVisible(true);
                telaDev.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoDevField;
    private javax.swing.JLabel codigoDevLabel;
    private javax.swing.JTextField dataDevDevField;
    private javax.swing.JLabel dataDevDevLabel;
    private javax.swing.JTextField dataEmpDevField;
    private javax.swing.JLabel dataEmpDevLabel;
    private javax.swing.JButton gerarDevButton;
    private javax.swing.JTextField isbnDevField;
    private javax.swing.JLabel isbnDevLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField quantidadeDevField;
    private javax.swing.JLabel quatidadeDevLabel;
    private javax.swing.JTextField statusDevField;
    private javax.swing.JLabel statusDevLabel;
    // End of variables declaration//GEN-END:variables
}
